name: rails

on:
  push:
    branches: '*'
  pull_request:
    branches:  '*'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'

    - name: Run Install
      run: |
        bundle install
    - name: Run Tests (rspec)
      run: |
        bundle exec rspec